package com.haraji.common.constant;

public enum ErrorCode {
    BAD_REQUEST,
    INVALID_FORMAT,
    FORBIDDEN,
    USER_NOT_FOUND,
    IDENTIFIER_ALREADY_EXISTS,
    INVALID_PASSWORD,
    USER_DISABLED,
    USER_LOCKED,
    USER_NOT_CREATED,
    DUPLICATE_IDENTIFIER,
    INVALID_OTP,
    OTP_EXPIRED,
    OTP_ALREADY_USED,
    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REVOKED,
    ACCESS_DENIED,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    ENTITY_NOT_FOUND,
    BUSINESS_TYPE_NOT_FOUND,
    CITY_NOT_FOUND
}
